#!/bin/bash

echo 
echo "Hello and welcome to my ruby class"
echo "This interface is so that users don't"
echo "need to install ruby on their computer"
echo "and can still participate"
echo 
echo "please fill out this info so we can proceed"
echo 
echo "name [A-Za-z]:"
read name

docker run -it -d --name="$name" ruby_class
if [ $? -ne 0 ]
then
  echo "looks like you already have a container I'll put you in it"
fi
exec docker exec -ti $name script -q -c "/bin/runner" /dev/null
